//Global quest script consts
_PLAYER_ACTION_PLAYER_CLICKED = "PLAYER_CLICKED";
_PLAYER_ACTION_NPC_CLICKED = "NPC_CLICKED";
_PLAYER_ACTION_ANSWER_CLICKED = "ANSWER_CLICKED";
_PLAYER_ACTION_CONTINUE = "CONTINUE";

_PLAYER_ACTION_DEFINES = {
	_PLAYER_ACTION_PLAYER_AVATAR_CLICKED : true,
	_PLAYER_ACTION_ANSWER_CLICKED : true,
	_PLAYER_ACTION_NPC_CLICKED : true,
	_PLAYER_ACTION_CONTINUE : true
};

_UI_ACTION_PHRASE ="PHRASE";
_UI_ACTION_QUIZ = "QUIZ";
_UI_ACTION_ANIMATION = "ANIMATION";
_UI_ACTION_STAGE_CLEAR = "STAGE_CLEAR";
_UI_ACTION_DELAY = "DELAY";

_UI_ACTION_DEFINES = {
	_UI_ACTION_PHRASE : true,
	_UI_ACTION_QUIZ : true,
	_UI_ACTION_ANIMATION : true,
	_UI_ACTION_STAGE_CLEAR : true,
	_UI_ACTION_DELAY : true
};

_UI_ACTOR_PLAYER = "PLAYER";
_UI_ACTOR_NPC = "NPC";

_UI_ACTOR_DEFINES = {
	_UI_ACTOR_PLAYER : true,
	_UI_ACTOR_NPC : true
};

_NODE_FLAG_DEFAULT = "DEFAULT";
_UI_ACTION_FLAG_STAGE_RESTART = "STAGE_RESTART";